pacman:
  repo:
  - name: core
    priority: 100
    server: https://mirrors.bfsu.edu.cn/archlinux/core/os/${arch}
  - name: extra
    priority: 110
    server: https://mirrors.bfsu.edu.cn/archlinux/extra/os/${arch}
  - name: multilib
    priority: 120
    server: https://mirrors.bfsu.edu.cn/archlinux/multilib/os/${arch}
  trust:
  - eworm@archlinux.org
  - dvzrv@archlinux.org
  - bluewind@archlinux.org
  - demize@archlinux.org
  - artafinde@archlinux.org
  - anthraxx@archlinux.org
  - foxboron@archlinux.org
  install:
  - core/archlinux-keyring
