pacman:
  repo:
  - name: archlinuxcn
    priority: 500
    server: https://repo.archlinuxcn.org/$$arch
  trust:
  - farseerfc@archlinux.org
  - lilac@build.archlinuxcn.org
  install:
  - archlinuxcn/archlinuxcn-keyring
