pacman:
  repo:
  - name: core
    priority: 100
    server: https://geo.mirror.pkgbuild.com/$$repo/os/$$arch
  - name: extra
    priority: 110
    server: https://geo.mirror.pkgbuild.com/$$repo/os/$$arch
  - name: multilib
    priority: 120
    server: https://geo.mirror.pkgbuild.com/$$repo/os/$$arch
  trust:
  - eworm@archlinux.org
  - dvzrv@archlinux.org
  - bluewind@archlinux.org
  - demize@archlinux.org
  - artafinde@archlinux.org
  - anthraxx@archlinux.org
  - foxboron@archlinux.org
  install:
  - core/archlinux-keyring
