pacman:
  repo:
  - name: blackarch
    priority: 1000
    server: https://mirrors.bfsu.edu.cn/blackarch/blackarch/os/${arch}
  trust:
  - noptrix@nullsecurity.net
  install:
  - blackarch/blackarch-keyring
