pacman:
  repo:
  - name: renegade-project
    priority: 200
    server: https://mirror.renegade-project.tech/arch/$$arch
  trust:
  - renegade-project@classfun.cn
  install:
  - renegade-project/renegade-project-keyring
