# Plasma KDE desktop
pacman:
  install:
  - plasma
  - konsole
  - kate
  - dolphin
  - sddm
  - packagekit-qt6
systemd:
  default: graphical.target
  enable:
  - sddm.service
filesystem:
  files:
  - path: /etc/sddm.conf.d/breeze.conf
    content: |
      [Theme]
      Current=breeze
+also:
# Ensure NetworkManager is enabled
- packages/network-manager
- packages/firefox
