filesystem:
  files:
  - path: /etc/systemd/scripts/automated-script.sh
    stage: pre-user
    content: |
      #!/usr/bin/env bash
      get_cmdline() {
        local param
        for param in $$(</proc/cmdline); do
          case "$${param}" in
            "$${1}="*)
              echo "$${param##*=}"
              return 0
            ;;
          esac
        done
      }
      automated_script() {
        local script rt
        script="$$(get_cmdline script)"
        if [[ -n "$${script}" && ! -x /tmp/startup_script ]]; then
          if [[ "$${script}" =~ ^((http|https|ftp|tftp)://) ]]; then
            echo "downloading $${script}"
            curl "$${script}" --retry-connrefused --retry 10 --retry-delay 10 -fsSL -o /tmp/startup_script
            rt="$$?"
          else
            cp "$${script}" /tmp/startup_script
            rt="$$?"
          fi
          if [[ "$${rt}" -eq 0 ]]; then
            chmod +x /tmp/startup_script
            echo "executing automated script"
            /tmp/startup_script
            rt="$$?"
            if [[ "$${rt}" -eq 0 ]]; then
              touch /tmp/startup_script_done
            fi
          fi
          return "$${rt}"
        fi
      }
      if ! [[ -f /tmp/startup_script_done ]]; then
        automated_script
      fi

  - path: /etc/systemd/system/automated-script.service
    stage: pre-user
    content: |
      [Unit]
      Description=Execute automated script from the kernel command line
      ConditionKernelCommandLine=script
      After=network-online.target
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=bash /etc/systemd/scripts/automated-script.sh
      SyslogIdentifier=automated-script
      [Install]
      WantedBy=default.target

systemd:
  enable:
  - automated-script.service
