filesystem:
  files:
  - path: /etc/systemd/system/pacman-init.service
    stage: pre-user
    content: |
      [Unit]
      Description=Initializes Pacman keyring
      ConditionPathIsReadWrite=/etc/pacman.d
      ConditionPathExists=!/etc/pacman.d/gnupg
      After=time-sync.target
      Before=archlinux-keyring-wkd-sync.service
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      TimeoutStartSec=infinity
      ExecStart=/usr/bin/pacman-key --init
      ExecStart=/usr/bin/pacman-key --populate
      [Install]
      WantedBy=multi-user.target
systemd:
  enable:
  - pacman-init.service
scripts:
- stage: pre-initramfs
  chroot: yes
  code: rm --one-file-system -rf /etc/pacman.d/gnupg
