mirrors:
- name: bfsu
  repos:
  # ArchLinux
  - original: https://geo.mirror.pkgbuild.com/
    mirror: https://mirrors.bfsu.edu.cn/archlinux/

  # ArchLinux ARM
  - name: archlinuxarm
    original: http://mirror.archlinuxarm.org/
    mirror: https://mirrors.bfsu.edu.cn/archlinuxarm/

  # Arch4Edu
  - name: arch4edu
    original: https://repository.arch4edu.org/
    mirror: https://mirrors.bfsu.edu.cn/arch4edu/

  # ArchLinux CN
  - name: archlinuxcn
    original: https://repo.archlinuxcn.org/
    mirror: https://mirrors.bfsu.edu.cn/archlinuxcn/

  # BlackArch
  - name: blackarch
    original: https://www.blackarch.org/blackarch/
    mirror: https://mirrors.bfsu.edu.cn/blackarch/
