mirrors:
- name: nju
  repos:
  # ArchLinux
  - original: https://geo.mirror.pkgbuild.com/
    mirror: https://mirror.nju.edu.cn/archlinux/

  # ArchLinux ARM
  - name: archlinuxarm
    original: http://mirror.archlinuxarm.org/
    mirror: https://mirror.nju.edu.cn/archlinuxarm/

  # Arch4Edu
  - name: arch4edu
    original: https://repository.arch4edu.org/
    mirror: https://mirror.nju.edu.cn/arch4edu/

  # ArchLinux CN
  - name: archlinuxcn
    original: https://repo.archlinuxcn.org/
    mirror: https://mirror.nju.edu.cn/archlinuxcn/

  # ArchRiscV
  - name: archriscv
    original: https://archriscv.felixc.at/
    mirror: https://mirror.nju.edu.cn/archriscv/

  # BlackArch
  - name: blackarch
    original: https://www.blackarch.org/blackarch/
    mirror: https://mirror.nju.edu.cn/blackarch/
