pacman:
  install:
  - networkmanager
systemd:
  enable:
  - NetworkManager.service
  - systemd-resolved.service
scripts:
- stage: pre-initramfs
  chroot: yes
  code: |
    rm -fv /etc/systemd/network/20-{ethernet,wlan,wwan}.network
