filesystem:
  files:
    - path: /etc/systemd/network/20-ethernet.network
      content: |
        [Match]
        Name=en*
        Name=eth*
        [Network]
        DHCP=yes
        IPv6PrivacyExtensions=yes
        [DHCPv4]
        RouteMetric=100
        [IPv6AcceptRA]
        RouteMetric=100
    - path: /etc/systemd/network/20-wlan.network
      content: |
        [Match]
        Name=wl*
        [Network]
        DHCP=yes
        IPv6PrivacyExtensions=yes
        [DHCPv4]
        RouteMetric=600
        [IPv6AcceptRA]
        RouteMetric=600
    - path: /etc/systemd/network/20-wwan.network
      content: |
        [Match]
        Name=ww*
        [Network]
        DHCP=yes
        IPv6PrivacyExtensions=yes
        [DHCPv4]
        RouteMetric=700
        [IPv6AcceptRA]
        RouteMetric=700
systemd:
  enable:
  - systemd-networkd.service
  - systemd-resolved.service
