# USB Gadget tools
pacman:
  install:
  - systemd-gadget
  - dnsmasq
systemd:
  disable:
  # Disable tty ACM to avoid bugs
  - getty@ttyGS0.service
  - usbgadget-func-acm.service
  enable:
  - gadget-init.service
  - gadget-start.service
  - usbgadget-func-rndis.service
  # Enable systemd-networkd for RNDIS
  - systemd-networkd.service
filesystem:
  files:
  - path: /etc/systemd/network/sharenet.network.d/override.conf
    content: |
      [DHCPServer]
      EmitRouter=no
      EmitDNS=no
