filesystem:
  files:
    # Network configs from archiso
    - path: /etc/systemd/network/20-ethernet.network
      stage: pre-user
      content: |
        [Match]
        Name=en*
        Name=eth*
        [Network]
        DHCP=yes
        IPv6PrivacyExtensions=yes
        [DHCPv4]
        RouteMetric=100
        [IPv6AcceptRA]
        RouteMetric=100
    - path: /etc/systemd/network/20-wlan.network
      stage: pre-user
      content: |
        [Match]
        Name=wl*
        [Network]
        DHCP=yes
        IPv6PrivacyExtensions=yes
        [DHCPv4]
        RouteMetric=600
        [IPv6AcceptRA]
        RouteMetric=600
    - path: /etc/systemd/network/20-wwan.network
      stage: pre-user
      content: |
        [Match]
        Name=ww*
        [Network]
        DHCP=yes
        IPv6PrivacyExtensions=yes
        [DHCPv4]
        RouteMetric=700
        [IPv6AcceptRA]
        RouteMetric=700
scripts:
- stage: pre-user
  chroot: yes
  code: ln -vsf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
systemd:
  enable:
  - systemd-networkd.service
  - systemd-resolved.service
