name: Generic ARM64 SBSA UEFI
target: aarch64-sbsa
arch: aarch64
pacman:
  install:
  - efibootmgr
  - grub
  - gcc-libs

grub:
  path: /boot/grub
  targets:
  - arm64-efi

fstab:
  dev: partlabel

bootloader:
  timeout: 3
  method:
  - grub
  items:
  - type: linux
    default: yes
    name: ${distro.name}
    path: /
    kernel: /boot/${kernel.kernel}
    initramfs: /boot/${kernel.initramfs}
    cmdline: ${@kernel.cmdline} ro quiet splash
  - type: linux
    name: ${distro.name} Fallback
    path: /
    kernel: /boot/${kernel.kernel}
    initramfs: /boot/initramfs-linux-mainline-aarch64-fallback.img
    cmdline: ${@kernel.cmdline} rw loglevel=7

+also:
- device/aarch64-sbsa
- target/partitions/uefi-boot
