name: Generic ARM64 SBSA UEFI
target: aarch64-sbsa
arch: aarch64
pacman:
  install:
  - efibootmgr
  - grub

image:
- type: disk
  output: disk.img
  layout: gpt
  size: 2GiB
  sector: 512
  partitions:
  - type: filesystem
    ptype: efi
    pname: esp
    size: 4MiB
    fsname: ESP
    fstype: fat12
    mount: /boot/efi
    fstab:
      flags: rw,noatime,utf8,errors=remount-ro
  - type: filesystem
    ptype: linux-root-arm64
    pname: linux
    fsname: ArchLinux
    fstype: ext4
    mount: /
    grow: yes
    fstab:
      boot: yes
      flags: rw,noatime,discard

grub:
  path: /boot/grub
  targets:
  - arm64-efi

fstab:
  dev: partlabel

bootloader:
  timeout: 3
  method:
  - grub
  items:
  - type: linux
    default: yes
    name: Arch Linux ARM
    path: /
    kernel: /boot/${kernel.kernel}
    initramfs: /boot/${kernel.initramfs}
    cmdline: ${@kernel.cmdline} ro quiet splash
  - type: linux
    name: Arch Linux ARM Fallback
    path: /
    kernel: /boot/${kernel.kernel}
    initramfs: /boot/initramfs-linux-mainline-aarch64-fallback.img
    cmdline: ${@kernel.cmdline} rw loglevel=7

+also:
- device/aarch64-sbsa
