name: Avaota C1
target: avaota-c1
arch: aarch64
firmware:
  uboot-spl: /boot/u-boot-sunxi-with-spl.bin
fstab:
  dev: partlabel
bootloader:
  timeout: 3
  method:
  - systemd-boot
  - extlinux
  items:
  - type: linux
    default: yes
    id: ${distro.identifier.id}-avaota-c1
    name: ${distro.name} for Avaota C1
    path: ${kernel.path}
    kernel: /${kernel.kernel}
    initramfs: /${kernel.initramfs}
    devicetree: /dtbs/allwinner/sun50i-h616-avaota-c1.dtb
    cmdline: ${@kernel.cmdline}
  - type: linux
    id: ${distro.identifier.id}-avaota-c2
    name: ${distro.name} for Avaota C2
    path: ${kernel.path}
    kernel: /${kernel.kernel}
    initramfs: /${kernel.initramfs}
    devicetree: /dtbs/allwinner/sun50i-h618-avaota-c2.dtb
    cmdline: ${@kernel.cmdline}
  - type: linux
    id: ${distro.identifier.id}-yuzuki-chameleon
    name: ${distro.name} for Yuzuki Chameleon
    path: ${kernel.path}
    kernel: /${kernel.kernel}
    initramfs: /${kernel.initramfs}
    devicetree: /dtbs/allwinner/sun50i-h616-yuzuki-chameleon.dtb
    cmdline: ${@kernel.cmdline}
mkinitcpio:
  no_fallback: yes
+also:
- device/avaota-c1
- packages/resize-rootfs
- target/partitions/allwinner
