name: Radxa ROCK 4A
target: rock-4a
arch: aarch64
firmware:
  idbloader: /usr/lib/firmware/radxa/rock4c/idbloader.img
  u-boot: /usr/lib/firmware/radxa/rock4c/u-boot.itb
fstab:
  dev: partuuid
bootloader:
  timeout: 3
  method:
  - systemd-boot
  - extlinux
mkinitcpio:
  no_fallback: yes
+also:
- device/radxa-rock-4a
- packages/resize-rootfs
- target/partitions/rockchip
- common/default-boot
