name: Generic x86_64 compatible PC Dual Boot
target: x86_64-dual
arch: x86_64
pacman:
  install:
  - grub
  - amd-ucode
  - intel-ucode
  - efibootmgr
fstab:
  dev: partlabel
kernel:
  kernel: /boot/vmlinuz-linux
  initramfs: /boot/initramfs-linux.img
  cmdline:
  - add_efi_memmap
grub:
  path: /boot/grub
  targets:
  - x86_64-efi
  - i386-efi
  - i386-pc
bootloader:
  timeout: 3
  method:
  - grub
  items:
  - type: linux
    default: yes
    name: Arch Linux
    path: /
    kernel: ${kernel.kernel}
    initramfs: ${kernel.initramfs}
    cmdline: ${@kernel.cmdline} ro quiet splash
  - type: linux
    name: Arch Linux Fallback
    path: /
    kernel: ${kernel.kernel}
    initramfs: /boot/initramfs-linux-fallback.img
    cmdline: ${@kernel.cmdline} rw loglevel=7
+also:
- device/x86_64
- target/partitions/dual-x86
