#
# Server Base System Architecture
#

name: Generic ARM64 SBSA
device: aarch64-sbsa

pacman:
  install:
  - fastfetch
  - mkinitcpio

kernel:
  cmdline:
  - panic=30
  - loglevel=8
  - add_efi_memmap
  path: /boot

+also:
- os/archlinuxarm
- repo/renegade-project

# Universal Mainline Kernel
- packages/linux-mainline-aarch64

# Network Daemon
- packages/systemd-networkd

# OpenSSH Server
- packages/openssh

# Text editor
- packages/editor

# Root without password
- common/wheel-nopasswd

# Reinitialize pacman-key when boot
- common/pacman-init
