name: Avaota C1
arch: aarch64
soc: sun50i-h616
device: avaota-c1

pacman:
  install:
  # For regulatory.db
  - wireless-regdb

  # Bootloader
  - uboot-avaota-c2

  # Kernel
  - linux-sun50i-h616

sysconf:
  chassis: embedded

kernel:
  cmdline:
  - clk_ignore_unused
  - pd_ignore_unused
  - panic=30
  - loglevel=8
  path: /boot
  kernel: Image
  devicetree: dtbs/${platform}/${soc}-${device}.dtb

+also:
- os/archlinuxarm
- repo/renegade-project

# Generic allwinner related config
- device/allwinner

# USB Gadget tools
- packages/systemd-gadget

# Network Daemon
- packages/systemd-networkd

# Android Debug Bridge Daemon via USB Gadget
- packages/adbd

# OpenSSH Server
- packages/openssh

# Text editor
- packages/editor

# Bluetooth related services
- packages/bluez

# Root without password
- common/wheel-nopasswd

# Reinitialize pacman-key when boot
- common/pacman-init
