pacman:
  install:
    - zsh

filesystem:
  files:
    - path: /etc/skel/.bashrc
      stage: pre-user
      content: |
        if [ -n "$$BASH" ] && [[ "$$-" = *i* ]]; then
          exec zsh
        fi
